BEGIN;

ALTER TABLE animals
ADD COLUMN is_archived BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE animals
ADD COLUMN archived_at TIMESTAMPTZ NULL;

ALTER TABLE animals
ADD COLUMN archived_by UUID NULL
REFERENCES users(user_id)
ON DELETE SET NULL;

COMMIT;
